server:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: true
    cert_file: cert.pem
    key_file: key.pem

network:
  external_ip: 203.0.113.10
  internal_ip: 192.168.1.50

logging:
  level: DEBUG
  file: ../logs/server.log
